<?php

namespace AppBundle\Repository;

/**
 * ComentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentRepository extends \Doctrine\ORM\EntityRepository
{
}
