<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostTagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTagRepository extends EntityRepository
{
    public function findTagByName($slug)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:PostTag c WHERE c.tagName = :name');
        $query->setParameters(array('name' => $slug));

        return $query->getResult();
    }
}
