<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PostCategory;
use AppBundle\Entity\UserBloger;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getAllPosts($currentPage = 1)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.isPublished = :public')
            ->setParameter('public', 1)
            ->orderBy('p.id', 'DESC')
            ->getQuery();

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    public function getPostsByCategory(PostCategory $post_category, $currentPage = 1)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.category = :category')
            ->setParameter('category', $post_category)
            ->orderBy('p.id', 'DESC')
            ->getQuery();

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    public function getPostsByUser(UserBloger $user, $currentPage = 1)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->setParameter('user', $user)
            ->orderBy('p.id', 'DESC')
            ->getQuery();

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    public function getFiveMostPopular()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.count', 'DESC')
            ->getQuery();

        $paginator = $this->paginate($query);

        return $paginator;
    }

    public function paginate($dql, $page = 1, $limit = 3)
    {
        if ($page === null) {
            $page = 1;
        }
        $paginator = new Paginator($dql, $fetchJoinCollection = true);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return $paginator;
    }
}
