<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCategoryRepository extends EntityRepository
{
    public function findCategoryByName($slug)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:PostCategory c WHERE c.name = :name');
        $query->setParameters(array('name' => $slug));

        return $query->getResult();
    }
}
