<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Post;

/**
 * PostPointRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPointRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRepeatedPoint(User $user, Post $post)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:PostPoint c WHERE c.user = :user AND c.post = :post');
        $query->setParameters(array('user' => $user, 'post' => $post));

        return $query->getResult();
    }
}
