<?php

namespace AppBundle\Repository;

/**
 * UserBlogerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBlogerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByName($slug)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:UserBloger c WHERE c.nickName = :name');
        $query->setParameters(array('name' => $slug));

        return $query->getResult();
    }
}
