<?php

namespace AppBundle\Repository;

/**
 * UserBlogerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBlogerRepository extends \Doctrine\ORM\EntityRepository
{
}
